overblog_graphql:
    definitions:
        internal_error_message: "An error occurred, please retry later or contact us!"
        schema:
            query: Query
            mutation: Mutation
        mappings:
            auto_discover: false
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/src/Resources/config/graphql/types"
                    suffix: ~
