language: php

php:
  - 7.2

services:
  - sqlite3

before_install:
  - composer self-update

env:
  - SYMFONY_VERSION="4.0.*" DB=sqlite

before_script:
  - composer self-update
  - composer install --dev --no-interaction --prefer-source
  - php bin/console doctrine:database:create --env=test --no-interaction --quiet
  - php bin/console doctrine:schema:update --force --env=test --no-interaction --quiet
  - php bin/console doctrine:fixture:load --env=test --no-interaction --quiet
  - php bin/console cache:warmup --env=test --quiet

test:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500

script:
  - php bin/phpunit
