SectionEnum:
    type: enum
    config:
        description: "The fridge section list."
        values:
            Main:
                value: 1
                description: "Section Main."
            Door:
                value: 2
                description: "Section Door."
            Freezer:
                value: 3
                description: "Section Freezer."