ProductSortedInput:
    type: input-object
    config:
        description: "The sorted parameters list."
        fields:
            id:
                type: "OrderByEnum"
                description: "Order by ID."
            name:
                type: "OrderByEnum"
                description: "Order by Name."
            description:
                type: "OrderByEnum"
                description: "Order by Description."
            volume:
                type: "OrderByEnum"
                description: "Order by Volume."
            expirationDate:
                type: "OrderByEnum"
                description: "Order by Product expiration date."
            createdAt:
                type: "OrderByEnum"
                description: "Order by Create Date"